<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>My Scripts</text>

        <Action name="ClipboardToColor">
        <icon></icon>
        <text>Convert clipboard text to Foreground Color</text>
        <whatsThis>Scans your clipboard for text matching hexcode or rgb() format, then sets your Foreground Color to it.</whatsThis>
        <toolTip>Scans your clipboard for text matching hexcode or rgb() format, then sets your Foreground Color to it.</toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip>ClipboardColor</statusTip>
        </Action>
    </Actions>
</ActionCollection>